baseURL = "https://serbandrugas.github.io/serban-george-paul-drugas/"
title = "Serban-George-Paul Drugas"
theme = "ananke"
languageCode = "en"
defaultContentLanguage = "ro"
defaultContentLanguageInSubdir = true

[params]
  custom_css = ["css/custom.css"]
  featured_image = "https://unsplash.com"
  description = "Blogul meu despre istorie, lingvistică şi spiritualitate ortodoxă"
  footer_social_enable = true
  copy_right = "© 2026 Serban-George-Paul Drugas. Toate drepturile rezervate."
  [[menu.footer]]
    name = "facebook"
    url = "https://www.facebook.com/serban.drugas" 
  [[menu.footer]]
    name = "link"
    label = "Wix"
    url = "https://serbangpdrugas.wixsite.com/burebistas"
  [[menu.footer]]
    name = "link"
    label = "Webnode"
    url = "https://serban-george-paul-drugas.webnode.ro/"

[languages]
  [languages.ro]
    title = "Serban George Paul Drugas"
    weight = 1
    languageName = "Română"
    contentDir = "content/ro"
    [[languages.ro.menu.main]]
      name = "Blog"
      url = "/ro/blog/"
      weight = 10
    [[languages.ro.menu.main]]
      name = "Despre"
      url = "/ro/despre/"
      weight = 20
    [[languages.ro.menu.main]]
      name = "Portfolio"
      url = "/ro/portfolio/"
      weight = 30
    [[languages.ro.menu.main]]
      name = "Shop"
      url = "/ro/shop/"
      weight = 40
    [[languages.ro.menu.main]]
      name = "Admin"
      url = "/ro/admin/"
      weight = 50

  [languages.en]
    title = "Serban George Paul Drugas"
    weight = 2
    languageName = "English"
    contentDir = "content/en"
    [[languages.en.menu.main]]
      name = "Blog"
      url = "/en/blog/"
      weight = 10
    [[languages.en.menu.main]]
      name = "About"
      url = "/en/about/"
      weight = 20
    [[languages.en.menu.main]]
      name = "Portfolio"
      url = "/ro/portfolio/"
      weight = 30
    [[languages.en.menu.main]]
      name = "Shop"
      url = "/ro/shop/"
      weight = 40
    [[languages.en.menu.main]]
      name = "Admin"
      url = "/ro/admin/"
      weight = 50


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
