baseURL = "https://serbandrugas.github.io/serban-george-paul-drugas/"
title = "Serban-George-Paul Drugas"
theme = "ananke"
languageCode = "en"
defaultContentLanguage = "ro"
defaultContentLanguageInSubdir = true

[params]
  featured_image = "https://unsplash.com"
  description = "Blogul meu despre istorie, lingvistică şi spiritualitate ortodoxă"

[languages]
[languages.ro]
  title = "Serban George Paul Drugas"
  weight = 1
  languageName = "Română"
  contentDir = "content/ro"
  [[languages.ro.menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 10
  [[languages.ro.menu.main]]
    name = "Despre"
    url = "/despre/"
    weight = 20

[languages.en]
  title = "Serban George Paul Drugas"
  weight = 2
  languageName = "English"
  contentDir = "content/en"
  [[languages.en.menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 10
  [[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 20

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "JSON"]
  section = ["HTML", "RSS", "JSON"]

